[package]
name = "ekg"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
ntp-client = "0.1"
rumqttc = "0.24.0"
serde = "1.0.219"
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }
tokio-cron-scheduler = "0.14.0"
toml = "0.8.23"
